repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: detect-aws-credentials
    -   id: trailing-whitespace
        exclude: .*\.(md)$
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.21.0
    hooks:
    -   id: terraform_fmt
    -   id: terraform_validate
